# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Graded CS Projects
email: david.griswold@graded.br
description: >- # this means to ignore newlines until "baseurl:"
  Projects made by the CS classes at Graded

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  2021BunnyGames:
    title: 2021 Bunny Games
    description: <p>Would you like to play a game? </p><p>In this project, the Fall 2021 App Development class at <a href="https://graded.br">Graded</a> followed along with their teacher to build a basic 2d game where a bunny just wants to get a cookie. The students then had a few days to add their own spin.
    link: /2021/bunnygames.html
    image: /2021/bunnygamesSplash.png
    output: true
